[package]
name = "base"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua = { version = "0.10.3", features = ["luau"] }
luau = { path = "../luau" }
once_cell = "1.20.3"

[dependencies.windows]
version = "0.*"
features = [
    "Win32_System_LibraryLoader",
]